name: Membership HRT

on: 
  schedule:
    - cron: '*/3 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.PAT }}

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Use the appropriate version

    - name: Build project
      run: dotnet build

    - name: Install Selenium WebDriver
      run: dotnet add package Selenium.WebDriver --version 4.18.1

    - name: Install Selenium WebDriver.ChromeDriver
      run: dotnet add package Selenium.WebDriver.ChromeDriver --version 123.0.6312.5800
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Run tests headlessly
      run: dotnet test
      env: 
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        HRT_PASS: ${{ secrets.HRT_PASS }}
        MMP_PASS: ${{ secrets.MMP_PASS }}
        ASPNETCORE_ENVIRONMENT: Development
        CHROME_BIN: /usr/bin/google-chrome
        DISPLAY: :99.0
